import Head from "next/head";
import CommentModal from "../components/CommentModal";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { NextPage, GetServerSideProps } from "next";
import { UserType, ArticleType } from "@/types";
interface HomeProps {
  newsResults: ArticleType;
  randomUsersResults: UserType;
}

const Home: NextPage<HomeProps> = ({ newsResults, randomUsersResults }) => {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">
        {/* Sidebar */}
        <Sidebar />

        {/* Feed */}

        <Feed />

        {/* Widgets */}

        <Widgets
          newsResults={newsResults}
          randomUsersResults={randomUsersResults || null}
        />

        {/* Modal */}

        <CommentModal />
      </main>
    </div>
  );
};

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json

export const getServerSideProps: GetServerSideProps<HomeProps> = async () => {
  const newsResults = await fetch(
    "https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"
  ).then((res) => res.json());

  // Who to follow section

  let randomUsersResults = [];

  try {
    const res = await fetch(
      "https://randomuser.me/api/?results=30&inc=name,login,picture"
    );

    randomUsersResults = await res.json();
  } catch (e) {
    randomUsersResults = [];
  }

  // const randomUsersResults = await fetch(
  //   "https://randomuser.me/api/?results=30&inc=name,login,picture"
  // ).then((res) => res.json());

  return {
    props: {
      newsResults,
      randomUsersResults,
    },
  };
};

export default Home;
