import Head from "next/head";
import CommentModal from "../components/CommentModal";
import Feed from "../components/Feed";
import Sidebar from "../components/Sidebar";
import Widgets from "../components/Widgets";
import { NextPage, GetServerSideProps } from "next";
import { UserType, ArticleType } from "@/types";
interface HomeProps {
  newsResults: ArticleType;
  randomUsersResults: UserType;
}

const Home: NextPage<HomeProps> = ({ newsResults, randomUsersResults }) => {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen mx-auto">

        <Sidebar />

     

        <Feed />

     

        <Widgets
          newsResults={newsResults}
          randomUsersResults={randomUsersResults || null}
        />

    

        <CommentModal />
      </main>
    </div>
  );
};



export const getServerSideProps = async () => {
  const [newsResponse, randomUsersResponse] = await Promise.all([
    fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json"),
    fetch("https://randomuser.me/api/?results=30&inc=name,login,picture")
  ]);

  const newsResults = await newsResponse.json();
  const randomUsersResults = await randomUsersResponse.json();

  return {
    props: {
      newsResults,
      randomUsersResults
    }
  };
};


export default Home;
